/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AiActionPlanRouteImport } from './routes/ai-action-plan'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SearchConsoleRouteImport } from './routes/search-console'
import { Route as SeoHealthRouteImport } from './routes/seo-health'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as PagesPageIdRouteImport } from './routes/pages.$pageId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as ScanLiveRouteImport } from './routes/scan.live'
import { Route as ScanResultsRouteImport } from './routes/scan.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AiActionPlanRoute = AiActionPlanRouteImport.update({
  id: '/ai-action-plan',
  path: '/ai-action-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchConsoleRoute = SearchConsoleRouteImport.update({
  id: '/search-console',
  path: '/search-console',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoHealthRoute = SeoHealthRouteImport.update({
  id: '/seo-health',
  path: '/seo-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPageIdRoute = PagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => PagesRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLiveRoute = ScanLiveRouteImport.update({
  id: '/scan/live',
  path: '/scan/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan/results',
  path: '/scan/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRoute
  '/ai-action-plan': typeof AiActionPlanRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/checkout': typeof CheckoutRoute
  '/competitors': typeof CompetitorsRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/keywords': typeof KeywordsRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pages': typeof PagesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/search-console': typeof SearchConsoleRoute
  '/seo-health': typeof SeoHealthRoute
  '/settings': typeof SettingsRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/scan/live': typeof ScanLiveRoute
  '/scan/results': typeof ScanResultsRoute
  '/admin/': typeof AdminIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/ai-action-plan': typeof AiActionPlanRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/checkout': typeof CheckoutRoute
  '/competitors': typeof CompetitorsRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/keywords': typeof KeywordsRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pages': typeof PagesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/search-console': typeof SearchConsoleRoute
  '/seo-health': typeof SeoHealthRoute
  '/settings': typeof SettingsRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/scan/live': typeof ScanLiveRoute
  '/scan/results': typeof ScanResultsRoute
  '/admin': typeof AdminIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/scan': typeof ScanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRoute
  '/ai-action-plan': typeof AiActionPlanRoute
  '/ai-copilot': typeof AiCopilotRoute
  '/analytics': typeof AnalyticsRoute
  '/checkout': typeof CheckoutRoute
  '/competitors': typeof CompetitorsRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/keywords': typeof KeywordsRoute
  '/login': typeof LoginRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pages': typeof PagesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/search-console': typeof SearchConsoleRoute
  '/seo-health': typeof SeoHealthRoute
  '/settings': typeof SettingsRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/scan/live': typeof ScanLiveRoute
  '/scan/results': typeof ScanResultsRoute
  '/admin/': typeof AdminIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agency'
    | '/ai-action-plan'
    | '/ai-copilot'
    | '/analytics'
    | '/checkout'
    | '/competitors'
    | '/dashboard'
    | '/integrations'
    | '/keywords'
    | '/login'
    | '/opportunities'
    | '/pages'
    | '/register'
    | '/reports'
    | '/search-console'
    | '/seo-health'
    | '/settings'
    | '/issues/$issueId'
    | '/pages/$pageId'
    | '/projects/$projectId'
    | '/scan/live'
    | '/scan/results'
    | '/admin/'
    | '/issues/'
    | '/projects/'
    | '/scan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency'
    | '/ai-action-plan'
    | '/ai-copilot'
    | '/analytics'
    | '/checkout'
    | '/competitors'
    | '/dashboard'
    | '/integrations'
    | '/keywords'
    | '/login'
    | '/opportunities'
    | '/pages'
    | '/register'
    | '/reports'
    | '/search-console'
    | '/seo-health'
    | '/settings'
    | '/issues/$issueId'
    | '/pages/$pageId'
    | '/projects/$projectId'
    | '/scan/live'
    | '/scan/results'
    | '/admin'
    | '/issues'
    | '/projects'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agency'
    | '/ai-action-plan'
    | '/ai-copilot'
    | '/analytics'
    | '/checkout'
    | '/competitors'
    | '/dashboard'
    | '/integrations'
    | '/keywords'
    | '/login'
    | '/opportunities'
    | '/pages'
    | '/register'
    | '/reports'
    | '/search-console'
    | '/seo-health'
    | '/settings'
    | '/issues/$issueId'
    | '/pages/$pageId'
    | '/projects/$projectId'
    | '/scan/live'
    | '/scan/results'
    | '/admin/'
    | '/issues/'
    | '/projects/'
    | '/scan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgencyRoute: typeof AgencyRoute
  AiActionPlanRoute: typeof AiActionPlanRoute
  AiCopilotRoute: typeof AiCopilotRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CheckoutRoute: typeof CheckoutRoute
  CompetitorsRoute: typeof CompetitorsRoute
  DashboardRoute: typeof DashboardRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KeywordsRoute: typeof KeywordsRoute
  LoginRoute: typeof LoginRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PagesRoute: typeof PagesRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SearchConsoleRoute: typeof SearchConsoleRoute
  SeoHealthRoute: typeof SeoHealthRoute
  SettingsRoute: typeof SettingsRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ScanLiveRoute: typeof ScanLiveRoute
  ScanResultsRoute: typeof ScanResultsRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ScanIndexRoute: typeof ScanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-action-plan': {
      id: '/ai-action-plan'
      path: '/ai-action-plan'
      fullPath: '/ai-action-plan'
      preLoaderRoute: typeof AiActionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-console': {
      id: '/search-console'
      path: '/search-console'
      fullPath: '/search-console'
      preLoaderRoute: typeof SearchConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-health': {
      id: '/seo-health'
      path: '/seo-health'
      fullPath: '/seo-health'
      preLoaderRoute: typeof SeoHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdRouteImport
      parentRoute: typeof PagesRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/live': {
      id: '/scan/live'
      path: '/scan/live'
      fullPath: '/scan/live'
      preLoaderRoute: typeof ScanLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/results': {
      id: '/scan/results'
      path: '/scan/results'
      fullPath: '/scan/results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PagesRouteChildren {
  PagesPageIdRoute: typeof PagesPageIdRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesPageIdRoute: PagesPageIdRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgencyRoute: AgencyRoute,
  AiActionPlanRoute: AiActionPlanRoute,
  AiCopilotRoute: AiCopilotRoute,
  AnalyticsRoute: AnalyticsRoute,
  CheckoutRoute: CheckoutRoute,
  CompetitorsRoute: CompetitorsRoute,
  DashboardRoute: DashboardRoute,
  IntegrationsRoute: IntegrationsRoute,
  KeywordsRoute: KeywordsRoute,
  LoginRoute: LoginRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PagesRoute: PagesRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SearchConsoleRoute: SearchConsoleRoute,
  SeoHealthRoute: SeoHealthRoute,
  SettingsRoute: SettingsRoute,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ScanLiveRoute: ScanLiveRoute,
  ScanResultsRoute: ScanResultsRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ScanIndexRoute: ScanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
